<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="imu">

    <joint name="imu_sensor_joint" type="fixed">
        <axis xyz="0 0 1" />
        <origin xyz="${chassis_length} 0 ${chassis_height/2}" rpy="0 0 0"/>
        <parent link="chassis"/>
        <child link="imu_sensor_link"/>
    </joint>
     
    <link name="imu_sensor_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.02 0.02 0.02"/>
            </geometry>
        </visual>
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="0.00000015" ixy="0" ixz="0" iyy="0.00000015" iyz="0" izz="0.00000015" />
        </inertial>
    </link>

    <gazebo reference="imu_sensor_link">
        <gravity>true</gravity>
        <sensor name='imu_sensor' type='imu'>
            <always_on>1</always_on>
            <update_rate>1000</update_rate>
            <visualize>1</visualize>
            <topic>__default_topic__</topic>
            <plugin name='imu_plugin' filename='libgazebo_ros_imu_sensor.so'>
                <ros>
                    <!-- Will publish to /imu/data -->
                    <namespace>/camera</namespace>
                    <remapping>~/out:=imu</remapping>
                </ros>
                <bodyName>imu_sensor_link</bodyName>
                <updateRateHZ>10.0</updateRateHZ>
                <gaussianNoise>0.0</gaussianNoise>
                <xyzOffset>0 0 0</xyzOffset>
                <rpyOffset>0 0 0</rpyOffset>
            </plugin>
            <pose>0 0 0 0 0 0</pose>
        </sensor>
    </gazebo>
  
</robot>